### ISSUE TITLE
Unrecognized opcode: 22

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#369]
Very similar to #356 

I'm getting this:

```
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 6: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:154)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:62)
	at org.eolang.jeo.EoToBytecodeMojo.execute(EoToBytecodeMojo.java:64)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:400)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 34 more
Caused by: java.lang.ClassNotFoundException: org.eolang.benchmark.F
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 41 more
[ERROR] Failed to execute goal org.eolang:jeo-maven-plugin:0.2.8:eo-to-bytecode (eo-to-bytecode) on project benchmark: Execution eo-to-bytecode of goal org.eolang:jeo-maven-plugin:0.2.8:eo-to-bytecode failed: Bytecode creation for the 'org/eolang/benchmark/Main' class is not possible due to unmet preconditions.: Failed to write method BytecodeMethodProperties(access=137, name=j$main, descriptor=([Ljava/lang/String;)V, signature=null, exceptions=[]), because some of the opcodes are not recognized: Unrecognized opcode: 22
```

This is my code in `org.eolang.benchmark.F`:

```
package org.eolang.benchmark;
interface F {
    int foo();
}
```

This is `Main`:

```
package org.eolang.benchmark;
public class Main {
    public static void main(String... args) {
        App app = new App();
        long total = Long.parseLong(args[0]);
        long sum = 0L;
        for (long i = 0; i < total; ++i) {
            sum += app.run();
        }
        System.out.println(sum);
    }
}
```

**Comment by yegor256** [comment]
@volodya-lombrozo please, help

**Comment by volodya-lombrozo** [comment]
@yegor256 I'll solve it asap

**Comment by volodya-lombrozo** [comment]
@yegor256 could you try with the new version, please? '0.2.9'

**Comment by yegor256** [comment]
@volodya-lombrozo that's all I'm getting now:

```
[INFO] --- jeo:0.2.9:eo-to-bytecode (eo-to-bytecode) @ benchmark ---
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 6: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:154)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:62)
	at org.eolang.jeo.EoToBytecodeMojo.execute(EoToBytecodeMojo.java:64)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:400)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 34 more
Caused by: java.lang.ClassNotFoundException: org.eolang.benchmark.F
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 41 more
[INFO] App.xmir compiled into App.class (326 bytes)
[INFO] B.xmir compiled into B.class (315 bytes)
[INFO] A.xmir compiled into A.class (250 bytes)
[INFO] Main.xmir compiled into Main.class (557 bytes)
[INFO] F.xmir compiled into F.class (94 bytes)
[INFO]jectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
```

Maybe it would be beneficial to add more context to the exception thrown? Now it's not even clear which file caused the problem.

Moreover, the build doesn't break. I see the error in the log, but the build continues. This looks definitely like a bug.

**Comment by volodya-lombrozo** [comment]
@yegor256 The issue occurred because I used a bytecode class verifier to check if we correctly compiled a bytecode file. The verifier couldn't find the required classes. I have now fixed that.
_____

The detailed explanation:

The original problem arose from incorrect classloader usage by the Java ASM library. Since we integrate our plugin into the Maven pipeline, we need to add classes compiled in the `compile` phase to the classloader used in the `process-classes` phase. A similar problem was addressed here: https://github.com/objectionary/jeo-maven-plugin/pull/365

So, I just had to specify which classloader `CheckClassAdapter`  should use.

____
Regarding exception handling, I would like to provide more context, but the developers of the Java ASM library decided to [swallow the exception](https://gitlab.ow2.org/asm/asm/-/blob/master/asm-util/src/main/java/org/objectweb/asm/util/CheckClassAdapter.java?ref_type=heads#L1076).

```java
try {
    analyzer.analyze(classNode.name, method);
} catch (AnalyzerException e) {
    e.printStackTrace(printWriter);
}
```

**Comment by volodya-lombrozo** [comment]
@yegor256 could you try with the new version, please? `0.2.10`

**Comment by yegor256** [comment]
@volodya-lombrozo I'm sorry to be a PITA, but this is what I'm getting:

```
[INFO] --- jeo:0.2.10:eo-to-bytecode (eo-to-bytecode) @ benchmark ---
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 6: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:62)
	at org.eolang.jeo.EoToBytecodeMojo.execute(EoToBytecodeMojo.java:64)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: org.eolang.benchmark.F not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:400)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
Caused by: java.lang.ClassNotFoundException: org.eolang.benchmark.F
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 40 more
[INFO] App.xmir compiled into App.class (326 bytes)
[INFO] B.xmir compiled into B.class (315 bytes)
[INFO] A.xmir compiled into A.class (250 bytes)
[INFO] Main.xmir compiled into Main.class (557 bytes)
[INFO] F.xmir compiled into F.class (94 bytes)
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Do you use that example: https://github.com/objectionary/benchmark/tree/master/src/main/java/org/eolang/benchmark ?
I tried to reproduce it and didn't see the exception

**Comment by yegor256** [comment]
@volodya-lombrozo yes, I'm using this repo. I just pushed the latest version. Try to clone it and then `make`. I'll be surprised if you don't see the error.

**Comment by volodya-lombrozo** [comment]
@yegor256 

1. `git clone https://github.com/objectionary/benchmark.git`

```
Cloning into 'benchmark'...
remote: Enumerating objects: 119, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 119 (delta 52), reused 93 (delta 33), pack-reused 0
Receiving objects: 100% (119/119), 24.88 KiB | 404.00 KiB/s, done.
Resolving deltas: 100% (52/52), done.
```

2. `cd benchmark`
3. `make`

Result: 
```
  benchmark git:(master) make
base=before
mvn --activate-profiles "${base}" --update-snapshots clean package "-DfinalName=${base}" "-Ddirectory=${base}"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.eolang:benchmark >------------------------
[INFO] Building benchmark 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ benchmark ---
[INFO] Deleting /Users/lombrozo/Workspace/OpenSource/benchmark
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ benchmark ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/lombrozo/Workspace/OpenSource/benchmark/src/main/resources
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ benchmark ---
[INFO] No sources to compile
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ benchmark ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/lombrozo/Workspace/OpenSource/benchmark/src/test/resources
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ benchmark ---
[INFO] No sources to compile
[INFO] 
[INFO] --- surefire:3.1.2:test (default-test) @ benchmark ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ benchmark ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.983 s
[INFO] Finished at: 2023-12-25T15:31:53+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.3.0:jar (default-jar) on project benchmark: Error assembling JAR: /Users/lombrozo/Workspace/OpenSource/benchmark/pom.xml isn't a file. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
make: *** [before.jar] Error 1
```

**Comment by volodya-lombrozo** [comment]
and after it, the `benchmark` folder is deleted

**Comment by yegor256** [comment]
@volodya-lombrozo hm... I'm getting a totally different output on `make`

**Comment by yegor256** [comment]
@volodya-lombrozo what is your `make` version? Try `make --version`:

```
$ make --version
GNU Make 4.4.1
Built for aarch64-apple-darwin22.3.0
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Apparently, I use the outdated `make` version:
```
make --version             
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you try with `0.2.11`, not it should be definetly fixed. I checked on your example by using `mvn process-classes -Pafter` command.

**Comment by yegor256** [comment]
@volodya-lombrozo try to install a new one: `brew install make` and then use `/opt/homebrew/opt/make/libexec/gnubin/make`

**Comment by yegor256** [comment]
@volodya-lombrozo 0.2.11 works fine, thanks!
