### ISSUE TITLE
ClassNotFoundException: com.exam.BA

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#426]
I'm getting this:

```
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 4: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at org.eolang.jeo.representation.bytecode.BytecodeClass.bytecode(BytecodeClass.java:171)
	at org.eolang.jeo.representation.xmir.XmlBytecode.bytecode(XmlBytecode.java:97)
	at org.eolang.jeo.representation.EoRepresentation.toBytecode(EoRepresentation.java:103)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.recompile(ImprovementBytecodeFootprint.java:77)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eolang.jeo.improvement.ImprovementBytecodeFootprint.apply(ImprovementBytecodeFootprint.java:64)
	at org.eolang.jeo.AssembleMojo.execute(AssembleMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.TypeNotPresentException: Type java.lang.ClassNotFoundException: com.exam.BA not present
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:378)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:360)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isAssignableFrom(SimpleVerifier.java:348)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.binaryOperation(BasicVerifier.java:300)
	at org.objectweb.asm.tree.analysis.BasicVerifier.binaryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:569)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.exam.BA
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.getClass(SimpleVerifier.java:376)
	... 40 more

```

This looks weird, since I don't have `com.exam` package in my test suite.

**Comment by volodya-lombrozo** [comment]
@yegor256 Seems that optimization adds `com.exam` package.

As you can find, `fuse` goal just inserts `BA` class as is (without changing its package):
https://github.com/objectionary/ineo-maven-plugin/blob/d315a8524bf1e538b265205bc1542d7a2983ebc9/src/main/resources/org/eolang/ineo/fuse/fuse.xsl#L33

Here is the package that is set in `BA`, which is a `com.example` now:
https://github.com/objectionary/ineo-maven-plugin/blob/d315a8524bf1e538b265205bc1542d7a2983ebc9/src/main/resources/org/eolang/ineo/fuse/BA.xmir#L15

**Comment by yegor256** [comment]
@volodya-lombrozo you're right, thanks, submitted: https://github.com/objectionary/ineo-maven-plugin/issues/50

**Comment by volodya-lombrozo** [comment]
@yegor256 Can we close this issue then?

**Comment by yegor256** [comment]
@volodya-lombrozo why it's `com.exam` instead of `com.example`? If it would be `com.example` in the logs, I would find the problem by myself. Now, `com.exam` looks like a bug in jeo.

**Comment by volodya-lombrozo** [comment]
@yegor256 I've tried to check `ineo` plugin: https://github.com/objectionary/ineo-maven-plugin/issues/50#issuecomment-1903833002

All the test classes in the integration test has `com.example` package (I changed them manually), but `BA.xmir` has `com.exam` package (in the integration test).

**Comment by yegor256** [comment]
@volodya-lombrozo yes thanks
