### ISSUE TITLE
Unicode error in attribute name mapping

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#801]
I found it [here](https://github.com/objectionary/eo/actions/runs/11504087775/job/32022823173?pr=3427):

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.eolang.Phi does not have member field 'org.eolang.Phi Î¦' [in thread "ForkJoinPool-1-worker-1"]
2024-10-24T21:47:26.5072485Z 	at org.eolang.Phi.<clinit>(Unknown Source)
2024-10-24T21:47:26.5073694Z 	at EOorg.EOeolang.EOnet.EOsocketTest.connectsToLocalServerViaSocketObject(EOsocketTest.java:90)
2024-10-24T21:47:26.5075401Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-10-24T21:47:26.5076699Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-10-24T21:47:26.5082057Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:767)
2024-10-24T21:47:26.5083658Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2024-10-24T21:47:26.5085675Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2024-10-24T21:47:26.5087915Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
2024-10-24T21:47:26.5089725Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
2024-10-24T21:47:26.5091665Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
2024-10-24T21:47:26.5094008Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
2024-10-24T21:47:26.5096501Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
2024-10-24T21:47:26.5099158Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2024-10-24T21:47:26.5101556Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2024-10-24T21:47:26.5103650Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2024-10-24T21:47:26.5105741Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2024-10-24T21:47:26.5111468Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
2024-10-24T21:47:26.5113546Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
2024-10-24T21:47:26.5115727Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$8(TestMethodTestDescriptor.java:217)
```

Pay attention, the Unicode here is broken: `org.eolang.Phi Î¦`. The name of the file is `Φ`, not `Î¦`. I'm not sure whether jeo is guilty here.

**Comment by yegor256** [comment]
@volodya-lombrozo please, check

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.12`, title is `0.6.12`

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you try the new version, please?

**Comment by yegor256** [comment]
@volodya-lombrozo works on my machine now, thanks!
