### ISSUE TITLE
Bytecode produced by JEO failed to resolve preserved parameter names

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/jeo-maven-plugin#833]
I've setup this pipeline with Fat Spring example in the `src/it/spring-fat`:

`Receptionist.java`:

```java
@RestController
public class Receptionist {

    @GetMapping("/hello")
    public String greetings(@RequestParam final String who) {
        return String.format("Glad to see you, %s...%n", who);
    }
}
```

and `ApplicationTest.java`

```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class ApplicationTest {

    @Autowired
    private TestRestTemplate template;

    @LocalServerPort
    private int port;

    @Test
    void startupsServerAndMakesGetRequest() {
        final ResponseEntity<String> resp = this.template.getForEntity(
            String.format("http://localhost:%d/hello?who=FatSpring", this.port),
            String.class
        );
        Assertions.assertEquals(
            HttpStatus.OK,
            resp.getStatusCode(),
            "Status code is not OK"
        );
        Assertions.assertNotNull(
            resp.getBody(),
            "Response body is empty"
        );
        final String expected = "Glad to see you, Fat Spring";
        System.out.printf("Expected %s%n", expected);
        Assertions.assertTrue(
            resp.getBody().contains(expected),
            String.format(
                "Hello response is not correct. The body: %s%n should contain '%s'",
                resp.getBody(),
                expected
            )
        );
    }

}
```

now I run it:

```bash
mvn clean integration-test -Dinvoker.test=spring-fat -DskipTests -e
```

that invokes the following goals:

```text
clean test -e
```

and it fails:

```text
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eolang.jeo.spring.ApplicationTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [file:/Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat/target/classes/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/aliaksei/code/open/jeo-maven-plugin/target/local-repo/ch/qos/logback/logback-classic/1.2.12/logback-classic-1.2.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
10:31:21.166 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
10:31:21.171 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating BootstrapContext using constructor [public org.springframework.test.context.support.DefaultBootstrapContext(java.lang.Class,org.springframework.test.context.CacheAwareContextLoaderDelegate)]
10:31:21.189 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating TestContextBootstrapper for test class [org.eolang.jeo.spring.ApplicationTest] from class [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]
10:31:21.194 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [org.eolang.jeo.spring.ApplicationTest], using SpringBootContextLoader
10:31:21.196 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [org.eolang.jeo.spring.ApplicationTest]: class path resource [org/eolang/jeo/spring/ApplicationTest-context.xml] does not exist
10:31:21.196 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [org.eolang.jeo.spring.ApplicationTest]: class path resource [org/eolang/jeo/spring/ApplicationTestContext.groovy] does not exist
10:31:21.196 [main] INFO org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [org.eolang.jeo.spring.ApplicationTest]: no resource found for suffixes {-context.xml, Context.groovy}.
10:31:21.197 [main] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils - Could not detect default configuration classes for test class [org.eolang.jeo.spring.ApplicationTest]: ApplicationTest does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
10:31:21.217 [main] DEBUG org.springframework.test.context.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfiles] and class [org.eolang.jeo.spring.ApplicationTest]
10:31:21.247 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat/target/classes/org/eolang/jeo/spring/Application.class]
10:31:21.251 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Found @SpringBootConfiguration org.eolang.jeo.spring.Application for test class org.eolang.jeo.spring.ApplicationTest
10:31:21.293 [main] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - @TestExecutionListeners is not present for class [org.eolang.jeo.spring.ApplicationTest]: using defaults.
10:31:21.294 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
10:31:21.299 [main] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Skipping candidate TestExecutionListener [org.springframework.test.context.transaction.TransactionalTestExecutionListener] due to a missing dependency. Specify custom listener classes or make the default listener classes and their required dependencies available. Offending class: [org/springframework/transaction/interceptor/TransactionAttributeSource]
10:31:21.299 [main] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Skipping candidate TestExecutionListener [org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener] due to a missing dependency. Specify custom listener classes or make the default listener classes and their required dependencies available. Offending class: [org/springframework/transaction/interceptor/TransactionAttribute]
10:31:21.299 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@1d9b7cce, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@4d9e68d0, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@42e99e4a, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@14dd9eb7, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@52e6fdee, org.springframework.test.context.support.DirtiesContextTestExecutionListener@6c80d78a, org.springframework.test.context.event.EventPublishingTestExecutionListener@62150f9e, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@1a451d4d, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@7fa98a66, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@15ff3e9e, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@5fdcaa40, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@6dc17b83, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@5e0826e7]
10:31:21.301 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - Before test class: context [DefaultTestContext@74e52303 testClass = ApplicationTest, testInstance = [null], testMethod = [null], testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@47af7f3d testClass = ApplicationTest, locations = '{}', classes = '{class org.eolang.jeo.spring.Application}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true, server.port=0}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@57175e74, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@7bb58ca3, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@7f9fcf7f, org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@2357d90a, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@157632c9, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@5034c75a], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> false]], class annotated with @DirtiesContext [false] with mode [null].
10:31:21.307 [main] DEBUG org.springframework.test.context.support.DependencyInjectionTestExecutionListener - Performing dependency injection for test context [[DefaultTestContext@74e52303 testClass = ApplicationTest, testInstance = org.eolang.jeo.spring.ApplicationTest@7ec7ffd3, testMethod = [null], testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@47af7f3d testClass = ApplicationTest, locations = '{}', classes = '{class org.eolang.jeo.spring.Application}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true, server.port=0}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@57175e74, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@7bb58ca3, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@7f9fcf7f, org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@2357d90a, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@157632c9, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@5034c75a], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> false, 'org.springframework.test.context.event.ApplicationEventsTestExecutionListener.recordApplicationEvents' -> false]]].

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.18)

2024-11-04 10:31:21.437  WARN 5163 --- [           main] ory$DuplicateJsonObjectContextCustomizer : 

Found multiple occurrences of org.json.JSONObject on the class path:

	file:/Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat/target/classes/org/json/JSONObject.class
	jar:file:/Users/aliaksei/code/open/jeo-maven-plugin/target/local-repo/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class

You may wish to exclude one of them to ensure predictable runtime behavior

2024-11-04 10:31:21.443  INFO 5163 --- [           main] org.eolang.jeo.spring.ApplicationTest    : Starting ApplicationTest using Java 21.0.5 on aliakseimbp.local with PID 5163 (started by aliaksei in /Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat)
2024-11-04 10:31:21.443  INFO 5163 --- [           main] org.eolang.jeo.spring.ApplicationTest    : No active profile set, falling back to 1 default profile: "default"
2024-11-04 10:31:21.849  INFO 5163 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 0 (http)
2024-11-04 10:31:21.853  INFO 5163 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-11-04 10:31:21.853  INFO 5163 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.83]
2024-11-04 10:31:21.895  INFO 5163 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-11-04 10:31:21.895  INFO 5163 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 435 ms
2024-11-04 10:31:22.122  INFO 5163 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 50368 (http) with context path ''
2024-11-04 10:31:22.127  INFO 5163 --- [           main] org.eolang.jeo.spring.ApplicationTest    : Started ApplicationTest in 0.807 seconds (JVM running for 1.223)
2024-11-04 10:31:22.277  INFO 5163 --- [o-auto-1-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-11-04 10:31:22.277  INFO 5163 --- [o-auto-1-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-11-04 10:31:22.277  INFO 5163 --- [o-auto-1-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
2024-11-04 10:31:22.296 ERROR 5163 --- [o-auto-1-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.] with root cause

java.lang.IllegalArgumentException: Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.updateNamedValueInfo(Unknown Source) ~[classes/:na]
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.getNamedValueInfo(Unknown Source) ~[classes/:na]
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(Unknown Source) ~[classes/:na]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(Unknown Source) ~[classes/:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(Unknown Source) ~[classes/:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.DispatcherServlet.doService(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.FrameworkServlet.doGet(Unknown Source) ~[classes/:na]
	at javax.servlet.http.HttpServlet.service(Unknown Source) ~[classes/:na]
	at org.springframework.web.servlet.FrameworkServlet.service(Unknown Source) ~[classes/:na]
	at javax.servlet.http.HttpServlet.service(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source) ~[classes/:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source) ~[classes/:na]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(Unknown Source) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source) ~[classes/:na]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(Unknown Source) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source) ~[classes/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(Unknown Source) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(Unknown Source) ~[classes/:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.StandardHostValve.invoke(Unknown Source) ~[classes/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(Unknown Source) ~[classes/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(Unknown Source) ~[classes/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(Unknown Source) ~[classes/:na]
	at org.apache.coyote.http11.Http11Processor.service(Unknown Source) ~[classes/:na]
	at org.apache.coyote.AbstractProcessorLight.process(Unknown Source) ~[classes/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Unknown Source) ~[classes/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(Unknown Source) ~[classes/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(Unknown Source) ~[classes/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(Unknown Source) ~[classes/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(Unknown Source) ~[classes/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(Unknown Source) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.212 s <<< FAILURE! - in org.eolang.jeo.spring.ApplicationTest
[ERROR] startupsServerAndMakesGetRequest  Time elapsed: 0.205 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Status code is not OK ==> expected: <200 OK> but was: <500 INTERNAL_SERVER_ERROR>
	at org.eolang.jeo.spring.ApplicationTest.startupsServerAndMakesGetRequest(ApplicationTest.java:54)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ApplicationTest.startupsServerAndMakesGetRequest:54 Status code is not OK ==> expected: <200 OK> but was: <500 INTERNAL_SERVER_ERROR>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2024-11-04T10:31:22+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jeo-spring-fat-it: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jeo-spring-fat-it: There are test failures.

Please refer to /Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:289)
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:161)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:364)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1041)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:857)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Running post-build script: /Users/aliaksei/code/open/jeo-maven-plugin/target/it/spring-fat/verify.groovy
java.lang.AssertionError: BUILD FAILED. Expression: log.contains(BUILD SUCCESS)
	at org.codehaus.groovy.runtime.InvokerHelper.createAssertError(InvokerHelper.java:416)
	at Script1.run(Script1.groovy:26)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:460)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:495)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:469)
	at org.apache.maven.shared.scriptinterpreter.GroovyScriptInterpreter.evaluateScript(GroovyScriptInterpreter.java:85)
	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.executeRun(ScriptRunner.java:222)
	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.run(ScriptRunner.java:158)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runPostBuildHook(AbstractInvokerMojo.java:1957)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:1914)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:1584)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.lambda$runBuilds$4(AbstractInvokerMojo.java:1346)
	at org.apache.maven.plugins.invoker.JobExecutor.lambda$forEach$0(JobExecutor.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
*** end build.log for: spring-fat/pom.xml ***

[ERROR] -------------------------------------------------
[ERROR] 
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  spring-fat/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:25 min
[INFO] Finished at: 2024-11-04T10:31:23+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.7.0:run (default) on project jeo-maven-plugin: 1 build failed. See console output above for details. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.7.0:run (default) on project jeo-maven-plugin: 1 build failed. See console output above for details.
```

[no-params.log](https://github.com/user-attachments/files/17615189/no-params.log)

As far I understand, this problem happens because bytecode produced by JEO can not resolve preserved variable names as parameters, like this:

```java
@RequestParam final String who
```

**Comment by volodya-lombrozo** [comment]
@h1alexbel Thank for reporting the bug. I will take a look at it as soon, as possible.

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.6.15`, title is `0.6.15`

**Comment by h1alexbel** [comment]
@volodya-lombrozo now treats parameters as expected, nice!
