### ISSUE TITLE
Cannot decompile JEO bytecode listings: Classfile does not start with magic bytes

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/jeo-maven-plugin#897]
Consider this JEO bytecode listings:

```text
// class version 55.0 (55)
// access flags 0x21
public class org/eolang/jeo/MethodByte {
  // compiled from: MethodByte.java
  // access flags 0x1
  // access flags 0x1
  public <init>()V
   L0
    LINENUMBER 3 L0
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 1
  // access flags 0x9
  public static main([Ljava/lang/String;)V
   L0
    LINENUMBER 5 L0
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    INVOKESTATIC org/eolang/jeo/MethodByte.method ()B
    INVOKEVIRTUAL java/io/PrintStream.println (I)V
   L1
    LINENUMBER 6 L1
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    LDC "passed"
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/String;)V
   L2
    LINENUMBER 7 L2
    RETURN
    MAXSTACK = 2
    MAXLOCALS = 1
  // access flags 0x8
  static method()B
   L0
    LINENUMBER 9 L0
    BIPUSH 52
    IRETURN
    MAXSTACK = 1
    MAXLOCALS = 0
}
```

Then, I've tried to decompile this listing using `com.strobel.decompiler.Decompiler` and [krak2](https://github.com/Storyyeller/Krakatau). Both of them complain about the magic bytes:

```
java.lang.IllegalStateException: Wrong magic number: 791617635

	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:566)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at com.strobel.decompiler.Decompiler.decompile(Decompiler.java:49)
	at com.strobel.decompiler.Decompiler.decompile(Decompiler.java:26)
	at org.eolang.jeo.representation.BytecodeListingTest.convertsToPrettyString(BytecodeListingTest.java:95)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

Internally, it checks magic bytes:

```java
public static TypeDefinition readClass(final int options, final IMetadataResolver resolver, final Buffer b) {
        final long magic = b.readInt() & 0xFFFFFFFFL;

        if (magic != MAGIC) {
            throw new IllegalStateException("Wrong magic number: " + magic);
        }
        ...
```

and krak2:

```bash
$ krak2 dis MethodByte.class --out MethodByte.j
```

```text
disassemble MethodByte.class
Parse error in MethodByte.class: Classfile does not start with magic bytes. Are you sure you passed in a classfile?
Error: Finished with 1 errors
```

It seems that bytecode produced by JEO is not correct, as we can't decompile it back.

**Comment by h1alexbel** [comment]
@volodya-lombrozo WDYT?

**Comment by volodya-lombrozo** [comment]
@h1alexbel Could you please add a bit of context? Where and how exactly did you get `MethodByte.class`?
Also could your run the following command:
```sh
 xxd -l4 MethodByte.class
```

It should print the following:
```
00000000: cafe babe                                ....
```
If it's different, the `MethodByte.class` was somehow corrupted.

**Comment by h1alexbel** [comment]
@volodya-lombrozo I used decompiled listing, produced by `org.eolang.jeo.representation.BytecodeListing`. Input was a compiled java class `MethodByte`:

```java
package org.eolang.jeo;

public class MethodByte {
    public MethodByte() {
    }

    public static void main(String[] var0) {
        System.out.println(method());
        System.out.println("passed");
    }

    static byte method() {
        return 52;
    }
}
```

BytecodeListing transforms this class file into this:

```text
// class version 55.0 (55)
// access flags 0x21
public class org/eolang/jeo/MethodByte {
  // compiled from: MethodByte.java
  // access flags 0x1
  // access flags 0x1
  public <init>()V
   L0
    LINENUMBER 3 L0
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 1
  // access flags 0x9
  public static main([Ljava/lang/String;)V
   L0
    LINENUMBER 5 L0
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    INVOKESTATIC org/eolang/jeo/MethodByte.method ()B
    INVOKEVIRTUAL java/io/PrintStream.println (I)V
   L1
    LINENUMBER 6 L1
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    LDC "passed"
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/String;)V
   L2
    LINENUMBER 7 L2
    RETURN
    MAXSTACK = 2
    MAXLOCALS = 1
  // access flags 0x8
  static method()B
   L0
    LINENUMBER 9 L0
    BIPUSH 52
    IRETURN
    MAXSTACK = 1
    MAXLOCALS = 0
}
```

and then, I tried to decompile that listing and got an error:

```
Parse error in MethodByte.class: Classfile does not start with magic bytes. Are you sure you passed in a classfile?
```

**Comment by h1alexbel** [comment]
> @h1alexbel Could you please add a bit of context? Where and how exactly did you get `MethodByte.class`? Also could your run the following command:
> 
> ```shell
>  xxd -l4 MethodByte.class
> ```
> 
> It should print the following:
> 
> ```
> 00000000: cafe babe                                ....
> ```
> 
> If it's different, the `MethodByte.class` was somehow corrupted.

@volodya-lombrozo I've got:

```text
00000000: 2f2f 2063                                // c
```

Investigating how MethodByte is corrupted..

**Comment by volodya-lombrozo** [comment]
@h1alexbel We should obtain the bytecode not from the output of `BytecodeListing` (as it isn't reliable) but directly from the bytes. We can retrieve the bytecode bytes as follows:
https://github.com/objectionary/jeo-maven-plugin/blob/fea4f7b6261bbf74e74e26a70435efffe21141f8/src/main/java/org/eolang/jeo/representation/BytecodeRepresentation.java#L118

Most probably, you will change this line to something like:
```java
new JavaListing(this.input.value()).toString()
```

**Comment by h1alexbel** [comment]
@volodya-lombrozo got it!
